services:
  aidetector:
    build: ./detector
    image: "ghcr.io/stefharmens/ai-detector:latest"
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864

    volumes:
      - ./example:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  web:
    image: "ghcr.io/stefharmens/ai-detector-web:latest"
    depends_on:
      - aidetector
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "80:3000"
    volumes_from:
      - aidetector
