services:
  aidetector:
    build:
      context: https://github.com/StefHarmens/ai-detector.git#main:detector
    image: "ai-detector-fork:main"
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864

    environment:
      AIDETECTOR_MAX_BUFFERED_DETECTIONS: 60
      AIDETECTOR_MAX_PENDING_EXPORTS: 1

    volumes:
      - ./example/config.json:/app/config.json
      - ./example/app.json:/app/app.json
      - ./example/sprong24.mp4:/app/sprong24.mp4
      - ./example/detections/:/app/detections

  web:
    image: "ghcr.io/eschouten/ai-detector-web:latest"
    depends_on:
      - aidetector
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "80:3000"
    volumes_from:
      - aidetector
